# project  3

police dataset

The data is from Police Check post

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv(r"C:\Users\LENOVO\Data analysis project\3. Police Data.csv")

In [7]:
data

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

# instructions for data cleaning

# 1 Remove the column that only contain missing values

In [10]:
data.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [20]:
data.drop(columns="country_name", inplace=True)
data.drop(columns="search_type", inplace=True)

In [16]:
data["driver_age"].fillna(data["driver_age"].mean(), inplace =True)

In [17]:
data.isnull().sum()

stop_date                 0
stop_time                 0
driver_gender          4061
driver_age_raw         4054
driver_age                0
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

# question on filturing and data count

# 2  For Speeding, were Men and Women stopped ore often?

In [21]:
# speeding is reelated to violation column
# men and women related to gender column

In [23]:
#to find records containg speeding record
data[data.violation == 'Speeding']

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
4,3/14/2005,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
6,4/1/2005,17:30,M,1969.0,36.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65527,12/6/2012,15:26,F,1981.0,31.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
65529,12/6/2012,16:00,M,1994.0,18.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
65530,12/6/2012,17:54,F,1987.0,25.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,1954.0,58.0,White,Speeding,Speeding,False,Warning,False,0-15 Min,False
65534,12/7/2012,0:30,F,1985.0,27.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False

In [25]:
data[data.violation == 'Speeding'].driver_gender.value_counts()
# this shows that men has violeted more then femele

M    25517
F    11686
Name: driver_gender, dtype: int64

# question on Grupby

# 3 Does gender affect who gets searched during a stop

In [27]:
data.groupby('driver_gender').search_conducted.sum()

driver_gender
F     366
M    2113
Name: search_conducted, dtype: int64

In [30]:
data.search_conducted.value_counts()

False    63056
True      2479
Name: search_conducted, dtype: int64

# Question bsed on mapping and data-type casting

# 4 what is the mean stop_duration

In [37]:
data.stop_duration.value_counts()

0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: stop_duration, dtype: int64

In [39]:
#stop_duration has type of string so to find mean we have to change its data type
data['stop_duration']=data['stop_duration'].map({'0-15 Min' :7.5, '16-30 Min ':23, '30+ Min ':45 })

In [40]:
data

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.000000,White,Speeding,Speeding,False,Citation,False,7.5,False
1,1/18/2005,8:15,M,1965.0,40.000000,White,Speeding,Speeding,False,Citation,False,7.5,False
2,1/23/2005,23:15,M,1972.0,33.000000,White,Speeding,Speeding,False,Citation,False,7.5,False
3,2/20/2005,17:15,M,1986.0,19.000000,White,Call for Service,Other,False,Arrest Driver,True,NaN,False
4,3/14/2005,10:00,F,1984.0,21.000000,White,Speeding,Speeding,False,Citation,False,7.5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,F,1987.0,25.000000,White,Speeding,Speeding,False,Citation,False,7.5,False
65531,12/6/2012,22:22,M,1954.0,58.000000,White,Speeding,Speeding,False,Warning,False,7.5,False
65532,12/6/2012,23:20,M,1985.0,27.000000,Black,Equipment/Inspection Violation,Equipment,False,Citation,False,7.5,False
65533,12/7/2012,0:23,NaN,NaN,34.148984,NaN,NaN,NaN,False,NaN,NaN,NaN,False
65534,12/7/2012,0:30,F,1985.0,27.000000,White,Speeding,Speeding,False,Citation,False,7.5,False

In [42]:
data['stop_duration'].mean()

7.5

# question on Groupby,  describe

#  5  Compare the age of distribution for each violation

In [45]:
data.groupby('violation').driver_age.describe()

,count,mean,std,min,25%,50%,75%,max
violation,,,,,,,,
Equipment,6516.0,31.686363,11.373176,16.0,23.0,28.0,39.0,81.0
Moving violation,11926.0,36.725595,13.231582,15.0,25.0,35.0,46.0,86.0
Other,3583.0,40.178563,12.608331,16.0,30.0,40.0,49.5,86.0
Registration/plates,2243.0,32.658692,11.143450,16.0,24.0,30.0,40.0,74.0
Seat belt,3.0,30.333333,10.214369,23.0,24.5,26.0,34.0,42.0
Speeding,37204.0,33.264582,12.601601,15.0,23.0,30.0,42.0,88.0